name: BuildAndTest

on:
  push:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: "24"
    - name: Build Project 
      run: |
        npm install
        npm run build
    - name: deploy file
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.FTP_USERNAME }}
        server: 'sujiraw.kamelong.com'
        port: '22'
        local_path: './dist/*'
        remote_path: '/ftp_kamelong/WebDiaDev/'
        sftp_only: true
        password: ${{ secrets.FTP_PASSWORD }}
